from backend.db import connect
#from backend.queries.vehicle_queries import *
from backend.queries.add_queries import *
from backend.queries.find_queries import *
from backend.queries.delete_queries import *
from tkinter import *
import tkinter as tk
from tkinter import StringVar, IntVar, Button, Label, Entry, Toplevel

class Add_Delete_Accessory(Toplevel):
    def __init__(self, master=None):
        super().__init__(master=master)
        self.title("Accessories")
        self.geometry("600x600")
        self.configure(bg='#36454F')
        self.int_id = IntVar()
        self.int_type = StringVar()
        self.int_desc = StringVar()
        self.int_color = StringVar()
        self.connection = connect()
        self.ext_id = IntVar()
        self.ext_type = StringVar()
        self.ext_desc = StringVar()
        self.ext_color = StringVar()
        self.feat_id = IntVar()
        self.feat_type = StringVar()
        self.feat_desc = StringVar()
        self.con_id = IntVar()
        self.con_type = StringVar()
        self.con_desc = StringVar()
        self.hand_id = IntVar()
        self.hand_type = StringVar()
        self.hand_desc = StringVar()
        self.preform_id = IntVar()
        self.preform_type = StringVar()
        self.preform_desc = StringVar()
        self.pack_id = IntVar()
        self.pack_type = StringVar()
        self.pack_desc = StringVar()
        self.warr_id = IntVar()
        self.warr_type = StringVar()
        self.warr_desc = StringVar()
        self.safe_id = IntVar()
        self.safe_type = StringVar()
        self.safe_desc = StringVar()
        self.audio_id = IntVar()
        self.audio_type = StringVar()
        self.audio_desc = StringVar()
        #build section for adding interior
        self.interior_id_label = Label(self, text="Interior ID: ")
        self.interior_id_label.grid(column=0, row=0, pady=(20,0), padx=(10,0))
        self.interior_id_entry = Entry(self, width = 10, textvariable=self.int_id)
        self.interior_id_entry.grid(column=1, row=0, pady=(20,0), padx=(20,0))
        self.interior_type_label = Label(self, text="Interior Type: ")
        self.interior_type_label.grid(column=0, row=1, pady=(20,0), padx=(10,0))
        self.interior_type_entry = Entry(self, width = 10, textvariable=self.int_type)
        self.interior_type_entry.grid(column=1, row=1, pady=(20,0), padx=(20,0))
        self.interior_description_label = Label(self, text="Interior Description: ")
        self.interior_description_label.grid(column=0, row=2, pady=(20,0), padx=(10,0))
        self.interior_description_entry = Entry(self, width = 30, textvariable=self.int_desc)
        self.interior_description_entry.grid(column=1, row=2, pady=(20,0), padx=(20,0))
        self.interior_color_label = Label(self, text="Interior Color: ")
        self.interior_color_label.grid(column=0, row=3, pady=(20,0), padx=(10,0))
        self.interior_color_entry = Entry(self, width = 10, textvariable=self.int_color)
        self.interior_color_entry.grid(column=1, row=3, pady=(20,0), padx=(20,0))
        self.interior_add_button = Button(self, text="Add Interior", command=self.add_Interior)
        self.interior_add_button.grid(column=0, row = 4, pady=(20,0), padx=(20,0))
        self.interior_del_button = Button(self, text="Delete Interior", command=self.delete_Interior)
        self.interior_del_button.grid(column=1, row = 4, pady=(20,0), padx=(20,0))
        
        #Build section for adding exterior
        self.exterior_id_label = Label(self, text="Exterior ID: ")
        self.exterior_id_label.grid(column=0, row=5, pady=(20,0), padx=(10,0))
        self.exterior_id_entry = Entry(self, width = 10, textvariable=self.ext_id)
        self.exterior_id_entry.grid(column=1, row=5, pady=(20,0), padx=(20,0))
        self.exterior_type_label = Label(self, text="Exterior Type: ")
        self.exterior_type_label.grid(column=0, row=6, pady=(20,0), padx=(10,0))
        self.exterior_type_entry = Entry(self, width = 10, textvariable=self.ext_type)
        self.exterior_type_entry.grid(column=1, row=6, pady=(20,0), padx=(20,0))
        self.exterior_description_label = Label(self, text="Exterior Description: ")
        self.exterior_description_label.grid(column=0, row=7, pady=(20,0), padx=(10,0))
        self.exterior_description_entry = Entry(self, width = 30, textvariable=self.ext_desc)
        self.exterior_description_entry.grid(column=1, row=7, pady=(20,0), padx=(20,0))
        self.exterior_color_label = Label(self, text="Exterior Color: ")
        self.exterior_color_label.grid(column=0, row=8, pady=(20,0), padx=(10,0))
        self.exterior_color_entry = Entry(self, width = 10, textvariable=self.ext_color)
        self.exterior_color_entry.grid(column=1, row=8, pady=(20,0), padx=(20,0))
        self.exterior_add_button = Button(self, text="Add Exterior", command=self.add_Exterior)
        self.exterior_add_button.grid(column=0, row = 9, pady=(20,0), padx=(20,0))
        self.exterior_del_button = Button(self, text="Delete Exterior", command=self.delete_Exterior)
        self.exterior_del_button.grid(column=1, row = 9, pady=(20,0), padx=(20,0))
        #Build section for adding features
        self.feature_id_label = Label(self, text="Feature ID: ")
        self.feature_id_label.grid(column=0, row=10, pady=(20,0), padx=(10,0))
        self.feature_id_entry = Entry(self, width = 10, textvariable=self.feat_id)
        self.feature_id_entry.grid(column=1, row=10, pady=(20,0), padx=(20,0))
        self.feature_type_label = Label(self, text="Feature Type: ")
        self.feature_type_label.grid(column=0, row=11, pady=(20,0), padx=(10,0))
        self.feature_type_entry = Entry(self, width = 10, textvariable=self.feat_type)
        self.feature_type_entry.grid(column=1, row=11, pady=(20,0), padx=(20,0))
        self.feature_description_label = Label(self, text="Feature Description: ")
        self.feature_description_label.grid(column=0, row=12, pady=(20,0), padx=(10,0))
        self.feature_description_entry = Entry(self, width = 30, textvariable=self.feat_desc)
        self.feature_description_entry.grid(column=1, row=12, pady=(20,0), padx=(20,0))
        self.feature_add_button = Button(self, text="Add Feature", command=self.add_Feature)
        self.feature_add_button.grid(column=0, row = 13, pady=(20,0), padx=(20,0))
        self.feature_del_button = Button(self, text="Delete Feature", command=self.delete_Feature)
        self.feature_del_button.grid(column=1, row = 13, pady=(20,0), padx=(20,0))
        #Build Section for add control
        self.control_id_label = Label(self, text="Control ID: ")
        self.control_id_label.grid(column=0, row=14, pady=(20,0), padx=(10,0))
        self.control_id_entry = Entry(self, width = 10, textvariable=self.con_id)
        self.control_id_entry.grid(column=1, row=14, pady=(20,0), padx=(20,0))
        self.control_type_label = Label(self, text="Control Type: ")
        self.control_type_label.grid(column=0, row=15, pady=(20,0), padx=(10,0))
        self.control_type_entry = Entry(self, width = 10, textvariable=self.con_type)
        self.control_type_entry.grid(column=1, row=15, pady=(20,0), padx=(20,0))
        self.control_description_label = Label(self, text="Control Description: ")
        self.control_description_label.grid(column=0, row=16, pady=(20,0), padx=(10,0))
        self.control_description_entry = Entry(self, width = 30, textvariable=self.con_desc)
        self.control_description_entry.grid(column=1, row=16, pady=(20,0), padx=(20,0))
        self.control_add_button = Button(self, text="Add Control", command=self.add_Control)
        self.control_add_button.grid(column=0, row = 17, pady=(20,0), padx=(20,0))
        self.control_del_button = Button(self, text="Delete Control", command=self.delete_Control)
        self.control_del_button.grid(column=1, row = 17, pady=(20,0), padx=(20,0))
        #Build Section for adding handling
        self.handling_id_label = Label(self, text="Feature ID: ")
        self.handling_id_label.grid(column=2, row=0, pady=(20,0), padx=(10,0))
        self.handling_id_entry = Entry(self, width = 10, textvariable=self.hand_id)
        self.handling_id_entry.grid(column=3, row=0, pady=(20,0), padx=(20,0))
        self.handling_type_label = Label(self, text="Handling Type: ")
        self.handling_type_label.grid(column=2, row=1, pady=(20,0), padx=(10,0))
        self.handling_type_entry = Entry(self, width = 10, textvariable=self.hand_type)
        self.handling_type_entry.grid(column=3, row=1, pady=(20,0), padx=(20,0))
        self.handling_description_label = Label(self, text="Handling Description: ")
        self.handling_description_label.grid(column=2, row=2, pady=(20,0), padx=(10,0))
        self.handling_description_entry = Entry(self, width = 30, textvariable=self.hand_desc)
        self.handling_description_entry.grid(column=3, row=2, pady=(20,0), padx=(20,0))
        self.handling_add_button = Button(self, text="Add Handling", command=self.add_Handling)
        self.handling_add_button.grid(column=2, row = 3, pady=(20,0), padx=(20,0))
        self.handling_del_button = Button(self, text="Delete Handling", command=self.delete_Handling)
        self.handling_del_button.grid(column=3, row = 3, pady=(20,0), padx=(20,0))
        #Build Section for preformance 
        self.preform_id_label = Label(self, text="Preformance ID: ")
        self.preform_id_label.grid(column=2, row=4, pady=(20,0), padx=(10,0))
        self.preform_id_entry = Entry(self, width = 10, textvariable=self.preform_id)
        self.preform_id_entry.grid(column=3, row=4, pady=(20,0), padx=(20,0))
        self.preform_type_label = Label(self, text="Preformance Type: ")
        self.preform_type_label.grid(column=2, row=5, pady=(20,0), padx=(10,0))
        self.preform_type_entry = Entry(self, width = 10, textvariable=self.preform_type)
        self.preform_type_entry.grid(column=3, row=5, pady=(20,0), padx=(20,0))
        self.preform_description_label = Label(self, text="Preformance Description: ")
        self.preform_description_label.grid(column=2, row=6, pady=(20,0), padx=(10,0))
        self.preform_description_entry = Entry(self, width = 30, textvariable=self.preform_desc)
        self.preform_description_entry.grid(column=3, row=6, pady=(20,0), padx=(20,0))
        self.preform_add_button = Button(self, text="Add Preformance", command=self.add_Preformance)
        self.preform_add_button.grid(column=2, row = 7, pady=(20,0), padx=(20,0))
        self.preform_del_button = Button(self, text="Delete Preformance", command=self.delete_Preformance)
        self.preform_del_button.grid(column=3, row = 7, pady=(20,0), padx=(20,0))
        #Build Section for package
        self.package_id_label = Label(self, text="Package ID: ")
        self.package_id_label.grid(column=2, row=8, pady=(20,0), padx=(10,0))
        self.package_id_entry = Entry(self, width = 10, textvariable=self.pack_id)
        self.package_id_entry.grid(column=3, row=8, pady=(20,0), padx=(20,0))
        self.package_type_label = Label(self, text="Package Type: ")
        self.package_type_label.grid(column=2, row=9, pady=(20,0), padx=(10,0))
        self.package_type_entry = Entry(self, width = 10, textvariable=self.pack_type)
        self.package_type_entry.grid(column=3, row=9, pady=(20,0), padx=(20,0))
        self.package_description_label = Label(self, text="Package Description: ")
        self.package_description_label.grid(column=2, row=10, pady=(20,0), padx=(10,0))
        self.package_description_entry = Entry(self, width = 30, textvariable=self.pack_desc)
        self.package_description_entry.grid(column=3, row=10, pady=(20,0), padx=(20,0))
        self.package_add_button = Button(self, text="Add Package", command=self.add_Package)
        self.package_add_button.grid(column=2, row = 11, pady=(20,0), padx=(20,0))
        self.package_del_button = Button(self, text="Delete Package", command=self.delete_Package)
        self.package_del_button.grid(column=3, row = 11, pady=(20,0), padx=(20,0))
        #Build Section for Safety
        self.safety_id_label = Label(self, text="Safety/Security ID: ")
        self.safety_id_label.grid(column=4, row=0, pady=(20,0), padx=(10,0))
        self.safety_id_entry = Entry(self, width = 10, textvariable=self.safe_id)
        self.safety_id_entry.grid(column=5, row=0, pady=(20,0), padx=(20,0))
        self.safety_type_label = Label(self, text="Safety/Security Type: ")
        self.safety_type_label.grid(column=4, row=1, pady=(20,0), padx=(10,0))
        self.safety_type_entry = Entry(self, width = 10, textvariable=self.safe_type)
        self.safety_type_entry.grid(column=5, row=1, pady=(20,0), padx=(20,0))
        self.safety_description_label = Label(self, text="Safety/Security Description: ")
        self.safety_description_label.grid(column=4, row=2, pady=(20,0), padx=(10,0))
        self.safety_description_entry = Entry(self, width = 30, textvariable=self.safe_desc)
        self.safety_description_entry.grid(column=5, row=2, pady=(20,0), padx=(20,0))
        self.safety_add_button = Button(self, text="Add Safety/Security", command=self.add_Safety)
        self.safety_add_button.grid(column=4, row = 3, pady=(20,0), padx=(20,0))
        self.safety_del_button = Button(self, text="Delete Safety/Security", command=self.delete_Safety)
        self.safety_del_button.grid(column=5, row = 3, pady=(20,0), padx=(20,0))
        #Build Section for Warranty
        self.warranty_id_label = Label(self, text="Warranty ID: ")
        self.warranty_id_label.grid(column=4, row=4, pady=(20,0), padx=(10,0))
        self.warranty_id_entry = Entry(self, width = 10, textvariable=self.warr_id)
        self.warranty_id_entry.grid(column=5, row=4, pady=(20,0), padx=(20,0))
        self.warranty_type_label = Label(self, text="Warranty Type: ")
        self.warranty_type_label.grid(column=4, row=5, pady=(20,0), padx=(10,0))
        self.warranty_type_entry = Entry(self, width = 10, textvariable=self.warr_type)
        self.warranty_type_entry.grid(column=5, row=5, pady=(20,0), padx=(20,0))
        self.warranty_description_label = Label(self, text="Warranty Description: ")
        self.warranty_description_label.grid(column=4, row=6, pady=(20,0), padx=(10,0))
        self.warranty_description_entry = Entry(self, width = 30, textvariable=self.warr_desc)
        self.warranty_description_entry.grid(column=5, row=6, pady=(20,0), padx=(20,0))
        self.warranty_add_button = Button(self, text="Add Warranty", command=self.add_Warranty)
        self.warranty_add_button.grid(column=4, row = 7, pady=(20,0), padx=(20,0))
        self.warranty_del_button = Button(self, text="Delete Warranty", command=self.delete_Warranty)
        self.warranty_del_button.grid(column=5, row = 7, pady=(20,0), padx=(20,0))
        #Build Section for audio
        self.audio_id_label = Label(self, text="Audio ID: ")
        self.audio_id_label.grid(column=4, row=8, pady=(20,0), padx=(10,0))
        self.audio_id_entry = Entry(self, width = 10, textvariable=self.audio_id)
        self.audio_id_entry.grid(column=5, row=8, pady=(20,0), padx=(20,0))
        self.audio_type_label = Label(self, text="Audio Type: ")
        self.audio_type_label.grid(column=4, row=9, pady=(20,0), padx=(10,0))
        self.audio_type_entry = Entry(self, width = 10, textvariable=self.audio_type)
        self.audio_type_entry.grid(column=5, row=9, pady=(20,0), padx=(20,0))
        self.audio_description_label = Label(self, text="Audio Description: ")
        self.audio_description_label.grid(column=4, row=10, pady=(20,0), padx=(10,0))
        self.audio_description_entry = Entry(self, width = 30, textvariable=self.audio_desc)
        self.audio_description_entry.grid(column=5, row=10, pady=(20,0), padx=(20,0))
        self.audio_add_button = Button(self, text="Add Audio", command=self.add_Audio)
        self.audio_add_button.grid(column=4, row = 11, pady=(20,0), padx=(20,0))
        self.audio_del_button = Button(self, text="Delete Audio", command=self.delete_Audio)
        self.audio_del_button.grid(column=5, row = 11, pady=(20,0), padx=(20,0))
        
    def add_Interior(self):
        add_interior(self.connection, self.int_id.get(), self.int_type.get(), self.int_desc.get(), self.int_color.get())
    def delete_Interior(self):
        delete_interior(self.connection, self.int_id.get(), self.int_type.get())
    
    def add_Exterior(self):
        add_exterior(self.connection, self.ext_id.get(), self.ext_type.get(), self.ext_desc.get(), self.int_color.get())
    def delete_Exterior(self):
        delete_exterior(self.connection, self.ext_id.get(), self.ext_type.get())
    def add_Feature(self):
        add_features(self.connection, self.feat_id.get(), self.feat_type.get(), self.feat_desc.get())
    def delete_Feature(self):
        delete_features(self.connection, self.feat_id.get(), self.feat_type.get())
    def add_Control(self):
        add_control(self.connection, self.con_id.get(), self.con_type.get(), self.con_desc.get())
    def delete_Control(self):
        delete_control(self.connection, self.con_id.get(), self.con_type.get())
    def add_Handling(self):
        add_handling(self.connection, self.hand_id.get(), self.hand_type.get(), self.hand_desc.get())
    def delete_Handling(self):
        delete_handling(self.connection, self.hand_id.get(), self.hand_type.get())
    def add_Audio(self):
        add_audio(self.connection, self.audio_id.get(), self.audio_type.get(), self.audio_desc.get())
    def delete_Audio(self):
        delete_audio(self.connection, self.audio_id.get(), self.audio_type.get())
    def add_Preformance(self):
        add_performance(self.connection, self.preform_id.get(), self.preform_type.get(), self.preform_desc.get())
    def delete_Preformance(self):
        delete_preformance(self.connection, self.preform_id.get(), self.preform_type.get())
    def add_Package(self):
        add_package(self.connection, self.pack_id.get(), self.pack_type.get(), self.pack_desc.get())
    def delete_Package(self):
        delete_package(self.connection, self.pack_id.get(), self.pack_type.get())
    def add_Safety(self):
        add_safe_security(self.connection, self.safe_id.get(), self.safe_type.get(), self.safe_desc.get())
    def delete_Safety(self):
        delete_safe_security(self.connection, self.safe_id.get(), self.safe_type.get())
    def add_Warranty(self):
        add_warranty(self.connection, self.warr_id.get(), self.warr_type.get(), self.warr_desc.get())
    def delete_Warranty(self):
        delete_warranty(self.connection, self.warr_id.get(), self.warr_type.get())
